/* AUTO-GENERATED by csrc/scripts/gen_ply_tables.py. DO NOT EDIT. */
/* Authoritative PLY LALR(1) tables for the zxbc grammar. */
#ifndef ZXBC_PLY_TABLES_H
#define ZXBC_PLY_TABLES_H

#include <stddef.h>

#define PLY_N_TERM     144
#define PLY_END_ID     144   /* $end */
#define PLY_ERROR_ID   145   /* error */
#define PLY_NT_BASE    146
#define PLY_N_NONTERM  74
#define PLY_N_SYM      220
#define PLY_N_STATES   800
#define PLY_N_PROD     409

/* One (symbol_id -> value) entry in a state's action/goto row. */
typedef struct { int sym; int val; } PlyEntry;

/* Per-state row: sorted-by-sym entries for binary search (mirrors dict.get). */
typedef struct { const PlyEntry *ents; int n; } PlyRow;

/* Production metadata. */
typedef struct {
    int name_sym;   /* LHS nonterminal symbol id */
    int len;        /* RHS length */
    int rule;       /* action-function id (see ply_actions), -1 if none */
    const char *str; /* human-readable 'A -> B C' for debug/error */
} PlyProd;

extern const PlyRow ply_action[PLY_N_STATES];
extern const PlyRow ply_goto[PLY_N_STATES];
extern const PlyProd ply_prod[PLY_N_PROD];
extern const int ply_defaulted[PLY_N_STATES]; /* reduce id (-prod) or 0 if none */
extern const char *const ply_sym_name[PLY_N_SYM];

#endif /* ZXBC_PLY_TABLES_H */
