#!/usr/bin/env python3
# gen_ply_tables.py — emit the authoritative PLY LALR(1) tables for the
# zxbc grammar as C data, so the C parse engine makes the SAME shift/reduce
# decisions as Python's PLY parser (byte-for-byte). This does NOT invent a
# parser; it serialises PLY's own generated tables (action/goto/productions)
# built from src/zxbc/zxbparser.py + src/zxbc/zxblex.py.
#
# Output: csrc/zxbc/plyparser/ply_tables.h and ply_tables.c
#
# Symbol numbering convention (shared terminal/nonterminal id space):
#   terminals   : id == index in zxblex.tokens (0..N_TERM-1)
#   $end        : id == N_TERM
#   error       : id == N_TERM + 1
#   nonterminals: id == N_TERM + 2 + (sorted index)
#
# This is build-time tooling. It only READS the read-only Python reference.

import os
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, ROOT)

from src.zxbc import zxbparser  # noqa: E402
from src.zxbc.zxblex import tokens as TOKENS  # noqa: E402

OUT_DIR = os.path.join(ROOT, "csrc", "zxbc", "plyparser")


def cstr(s):
    out = []
    for ch in s:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return "".join(out)


def main():
    parser = zxbparser.parser
    action = parser.action
    goto = parser.goto
    productions = parser.productions
    defaulted = parser.defaulted_states

    n_term = len(TOKENS)
    END_ID = n_term
    ERROR_ID = n_term + 1

    # Build symbol id map.
    sym_id = {}
    for i, t in enumerate(TOKENS):
        sym_id[t] = i
    sym_id["$end"] = END_ID
    sym_id["error"] = ERROR_ID

    # Collect nonterminals (everything appearing as a production name or in goto)
    nonterms = set()
    for p in productions:
        nonterms.add(p.name)
    for st, g in goto.items():
        nonterms.update(g.keys())
    nonterms = sorted(nonterms)
    nt_base = n_term + 2
    for i, nt in enumerate(nonterms):
        sym_id[nt] = nt_base + i
    n_nonterm = len(nonterms)
    n_sym = nt_base + n_nonterm

    n_states = max(len(action), len(goto))
    # action/goto are dicts keyed by state int 0..n_states-1
    assert set(action.keys()) == set(range(len(action))), "action states not contiguous"

    # ---- distinct callables -> rule function ids ----
    # Production 0 is the augmented start S' -> start (no callable).
    rule_func_name = []  # per-production: callable __name__ or None
    for p in productions:
        c = getattr(p, "callable", None)
        rule_func_name.append(c.__name__ if c else None)

    # ---------- emit header ----------
    os.makedirs(OUT_DIR, exist_ok=True)
    h = []
    h.append("/* AUTO-GENERATED by csrc/scripts/gen_ply_tables.py. DO NOT EDIT. */")
    h.append("/* Authoritative PLY LALR(1) tables for the zxbc grammar. */")
    h.append("#ifndef ZXBC_PLY_TABLES_H")
    h.append("#define ZXBC_PLY_TABLES_H")
    h.append("")
    h.append("#include <stddef.h>")
    h.append("")
    h.append(f"#define PLY_N_TERM     {n_term}")
    h.append(f"#define PLY_END_ID     {END_ID}   /* $end */")
    h.append(f"#define PLY_ERROR_ID   {ERROR_ID}   /* error */")
    h.append(f"#define PLY_NT_BASE    {nt_base}")
    h.append(f"#define PLY_N_NONTERM  {n_nonterm}")
    h.append(f"#define PLY_N_SYM      {n_sym}")
    h.append(f"#define PLY_N_STATES   {n_states}")
    h.append(f"#define PLY_N_PROD     {len(productions)}")
    h.append("")
    h.append("/* One (symbol_id -> value) entry in a state's action/goto row. */")
    h.append("typedef struct { int sym; int val; } PlyEntry;")
    h.append("")
    h.append("/* Per-state row: sorted-by-sym entries for binary search (mirrors dict.get). */")
    h.append("typedef struct { const PlyEntry *ents; int n; } PlyRow;")
    h.append("")
    h.append("/* Production metadata. */")
    h.append("typedef struct {")
    h.append("    int name_sym;   /* LHS nonterminal symbol id */")
    h.append("    int len;        /* RHS length */")
    h.append("    int rule;       /* action-function id (see ply_actions), -1 if none */")
    h.append("    const char *str; /* human-readable 'A -> B C' for debug/error */")
    h.append("} PlyProd;")
    h.append("")
    h.append("extern const PlyRow ply_action[PLY_N_STATES];")
    h.append("extern const PlyRow ply_goto[PLY_N_STATES];")
    h.append("extern const PlyProd ply_prod[PLY_N_PROD];")
    h.append("extern const int ply_defaulted[PLY_N_STATES]; /* reduce id (-prod) or 0 if none */")
    h.append("extern const char *const ply_sym_name[PLY_N_SYM];")
    h.append("")
    h.append("#endif /* ZXBC_PLY_TABLES_H */")
    with open(os.path.join(OUT_DIR, "ply_tables.h"), "w") as f:
        f.write("\n".join(h) + "\n")

    # ---------- emit source ----------
    c = []
    c.append("/* AUTO-GENERATED by csrc/scripts/gen_ply_tables.py. DO NOT EDIT. */")
    c.append('#include "ply_tables.h"')
    c.append("")

    # symbol names
    sym_name = [None] * n_sym
    for name, i in sym_id.items():
        sym_name[i] = name
    c.append("const char *const ply_sym_name[PLY_N_SYM] = {")
    for i in range(n_sym):
        nm = sym_name[i] if sym_name[i] is not None else "?"
        c.append(f'    "{cstr(nm)}", /* {i} */')
    c.append("};")
    c.append("")

    # action rows. A None-valued entry in PLY's action dict is, for the parse
    # loop, identical to an absent key: actions[state].get(ltype) yields None
    # either way and falls into the error path. So drop None-valued entries.
    def filt(row):
        return {k: v for k, v in row.items() if v is not None}

    for st in range(n_states):
        row = filt(action.get(st, {}))
        items = sorted((sym_id[k], v) for k, v in row.items())
        if items:
            c.append(f"static const PlyEntry act_{st}[] = {{")
            line = "    "
            for s, v in items:
                line += f"{{{s},{v}}},"
                if len(line) > 90:
                    c.append(line)
                    line = "    "
            if line.strip():
                c.append(line)
            c.append("};")
    c.append("const PlyRow ply_action[PLY_N_STATES] = {")
    for st in range(n_states):
        row = filt(action.get(st, {}))
        n = len(row)
        if n:
            c.append(f"    {{act_{st}, {n}}},")
        else:
            c.append("    {0, 0},")
    c.append("};")
    c.append("")

    # goto rows
    for st in range(n_states):
        row = goto.get(st, {})
        items = sorted((sym_id[k], v) for k, v in row.items())
        if items:
            c.append(f"static const PlyEntry gto_{st}[] = {{")
            line = "    "
            for s, v in items:
                line += f"{{{s},{v}}},"
                if len(line) > 90:
                    c.append(line)
                    line = "    "
            if line.strip():
                c.append(line)
            c.append("};")
    c.append("const PlyRow ply_goto[PLY_N_STATES] = {")
    for st in range(n_states):
        row = goto.get(st, {})
        n = len(row)
        if n:
            c.append(f"    {{gto_{st}, {n}}},")
        else:
            c.append("    {0, 0},")
    c.append("};")
    c.append("")

    # productions (rule id filled later when actions are written; for now -1 placeholder
    # except we record a stable rule id == production index so the action dispatch is by
    # production number directly).
    c.append("const PlyProd ply_prod[PLY_N_PROD] = {")
    for i, p in enumerate(productions):
        name_sym = sym_id[p.name]
        rule = i if rule_func_name[i] else -1
        c.append(f'    {{{name_sym}, {p.len}, {rule}, "{cstr(p.str)}"}}, /* {i} */')
    c.append("};")
    c.append("")

    # defaulted states
    c.append("const int ply_defaulted[PLY_N_STATES] = {")
    line = "    "
    for st in range(n_states):
        v = defaulted.get(st, 0)
        line += f"{v},"
        if len(line) > 90:
            c.append(line)
            line = "    "
    if line.strip():
        c.append(line)
    c.append("};")
    c.append("")

    with open(os.path.join(OUT_DIR, "ply_tables.c"), "w") as f:
        f.write("\n".join(c) + "\n")

    # ---------- emit a manifest of production -> callable for Phase D wiring ----------
    man = []
    man.append("# production index -> name -> callable -> rule str")
    for i, p in enumerate(productions):
        man.append(f"{i}\t{p.name}\t{rule_func_name[i]}\t{p.str}")
    with open(os.path.join(OUT_DIR, "productions.tsv"), "w") as f:
        f.write("\n".join(man) + "\n")

    print(f"states={n_states} prod={len(productions)} term={n_term} "
          f"nonterm={n_nonterm} sym={n_sym} defaulted={len([v for v in defaulted.values() if v])}")
    print(f"wrote {OUT_DIR}/ply_tables.h, ply_tables.c, productions.tsv")


if __name__ == "__main__":
    main()
