/*
 * opts_embedded.c - the 52 embedded peephole .opt files,
 * copied VERBATIM as read-only data (CLAUDE.md rule 5: no
 * filesystem read, no external deps; shipped like the runtime
 * library). Generated from the live .opt bytes; each entry is an
 * exact byte copy (verified). The engine iterates THIS table
 * exactly as read_opts() iterates a directory listing.
 *
 * Order: sorted filename order. read_opts() then applies a STABLE
 * sort by OFLAG; sorted-filename is the deterministic listing the
 * Python loader is taken to observe (os.listdir order is otherwise
 * unspecified). DO NOT EDIT - regenerate from the opts directory.
 */
#include "opts_embedded.h"

const EmbeddedOpt PEEP_EMBEDDED_OPTS[] = {
  { "000_o1_push_pop.opt",
    ";; Remove sequence:\n;; push xx\n;; pop xx\n\nOLEVEL: 1\nOFLAG: 1\n\nREPLACE {{\n push $1\n pop $1\n}}\n\nWITH {{\n}}\n" },
  { "000_o3_push_pop.opt",
    ";; Remove sequence:\n;; push xx\n;; pop xx\n\nOLEVEL: 3\nOFLAG: 1\n\nREPLACE {{\n push $1\n pop $1\n}}\n\nWITH {{\n}}\n" },
  { "001_o1_ld_XXYY_ldYYXX.opt",
    ";; Replaces sequence:\n;; ld XX, YY\n;; ld YY, XX  ;; This is useless\n\n;; With:\n;; ld XX, YY\n\nOLEVEL: 1\nOFLAG: 2\n\nREPLACE {{\n ld $1, $2\n ld $2, $1\n}}\n\nWITH {{\n ld $1, $2\n}}\n" },
  { "002_o1_push_hlde_to_ex.opt",
    ";; Replaces sequence:\n;; push de\n;; push hl\n;; pop de\n;; pop hl\n\n;; with\n;; ex de, hl\n\nOLEVEL: 1\nOFLAG: 3\n\nREPLACE {{\n push $1\n push $2\n pop $1\n pop $2\n}}\n\nIF {{\n (($1 == hl) && ($2 == de)) || (($1 == de) && ($2 == hl))\n}}\n\nWITH {{\n ex de, hl\n}}" },
  { "003_o1_useless_jp.opt",
    ";; Replaces sequence:\n;;  jp XXX\n;;  XXX:\n;; with\n;;  XXX:\n;; (jp is useless here)\n\nOLEVEL: 1\nOFLAG: 4\n\nREPLACE {{\n jp$1 $2\n $2:\n}}\n\nWITH {{\n $2:\n}}" },
  { "004_o1_push_pop_ldld.opt",
    ";; Replaces sequence:\n;;  push hl\n;;  pop de\n;;  pop hl | ld hl, XX\n;; with\n;;  ex de, hl\n;;  pop hl  | ld hl, XX\n;; (also reverse order allowed)\n\nOLEVEL: 1\nOFLAG: 5\n\nREPLACE {{\n  ld d, h\n  ld e, l\n  $1 hl$2\n}}\n\nIF {{\n ($1 == pop) || ($1 == ld)\n}}\n\nWITH {{\n ex de, hl\n $1 hl$2\n}}\n\n" },
  { "005_o1_push_af_ld_aX.opt",
    ";; Replaces sequence:\n;;  ld a, (ix|iy +|- NNN)\n;;  inc|dec|cp a\n;;  ld (ix|iy +|- NNN), a\n;; with\n;;  inc|dec|cp (ix|iy +|- NNN)\n\nOLEVEL: 1\nOFLAG: 6\n\nREPLACE {{\n ld a, $1\n $2 a\n ld $1, a\n}}\n\nIF {{\n  (IS_INDIR($1) || ($1 == \"(hl)\")) && (($2 == cp) || ($2 == inc) || ($2 == dec))\n}}\n\nWITH {{\n $2 $1\n}}\n" },
  { "006_o1_push_af_pop_XX.opt",
    ";; Replaces sequence:\n;;  push af\n;;  pop XY\n;; with\n;;  ld X, a\n;; (also reverse order allowed)\n\nOLEVEL: 1\nOFLAG: 7\n\nREPLACE {{\n push $1\n pop $2\n}}\n\nIF {{\n  ($1 <> $2) && (($1 == af) || ($2 == af))\n}}\n\nDEFINE {{\n  $3 = HIREG($1)\n  $4 = HIREG($2)\n}}\n\nWITH {{\n ld $4, $3\n}}\n" },
  { "006_o3_push_af_pop_XX.opt",
    ";; Replaces sequence:\n;;  push af\n;;  pop XY\n;; with\n;;  ld X, a\n;; (also reverse order allowed)\n\nOLEVEL: 3\nOFLAG: 7\n\nREPLACE {{\n push $1\n pop $2\n}}\n\nIF {{\n  ($1 <> $2) && (($1 == af) || ($2 == af))\n}}\n\nDEFINE {{\n  $3 = HIREG($1)\n  $4 = HIREG($2)\n}}\n\nWITH {{\n ld $4, $3\n}}\n" },
  { "007_o1_ex_de_hl.opt",
    ";; Remove sequence:\n;; ex de, hl\n;; ex de, hl\n;;\n;; Also works with ex af, af' and exx\n\nOLEVEL: 1\nOFLAG: 8\n\nREPLACE {{\n ex$1\n ex$1\n}}\n\nWITH {{\n}}\n" },
  { "008_o1_sbc_jp.opt",
    ";; Replace sequence:\n;; sbc a, a\n;; or a\n;; jp z, __X\n;;\n;; With:\n;; jp nc, __X\n\nOLEVEL: 1\nOFLAG: 9\n\nREPLACE {{\n sbc a, a\n or a\n $1 $2, $3\n}}\n\nDEFINE {{\n $4 = (($2 == \"z\") && \"nc\") || (\"c\")\n}}\n\nIF {{\n    (($1 == \"jp\") || ($1 == \"jr\"))\n}}\n\nWITH {{\n  $1 $4, $3\n}}\n" },
  { "009_o1_inc_mem.opt",
    ";; Replace sequence:\n;; ld a, (xxx)\n;; inc a | dec a\n;; ld (xxx), a\n;;\n;; With:\n;; ld hl, xxx\n;; inc (hl) | dec (hl)\n\nOLEVEL: 1\nOFLAG: 10\n\nREPLACE {{\n  ld a, ($1)\n  $2 a\n  ld ($1), a\n}}\n\nDEFINE {{\n $3 = \"(\" + $1 + \")\"\n}}\n\nIF {{\n  (($2 == \"inc\") || ($2 == \"dec\")) && (($1 <> \"hl\") && (!IS_INDIR($3)))\n}}\n\nWITH {{\n  ld hl, $1\n  $2 (hl)\n}}\n" },
  { "010_o1_ld_de_hl_ex_de_hl.opt",
    ";; Replaces sequence:\n;;  push AB\n;;  pop CD\n;; With:\n;;  ld C, A\n;;  ld B, D\n\nOLEVEL: 1\nOFLAG: 11\n\nREPLACE {{\n push $1\n pop $2\n}}\n\nDEFINE {{\n  $3 = HIREG($1)\n  $4 = LOREG($1)\n  $5 = HIREG($2)\n  $6 = LOREG($2)\n}}\n\nIF {{\n  ($1 <> $2) &&\n  (($1 == hl) || ($1 == de) || ($1 == bc)) &&\n  (($2 == hl) || ($2 == de) || ($2 == bc))\n}}\n\nWITH {{\n ld $5, $3\n ld $6, $4\n}}\n\n" },
  { "011_o1_ld_h_a_pop_af_or_h.opt",
    ";; Replaces sequence:\n;;  ld h, a\n;;  pop af\n;;  or h | and h | xor h\n;; With:\n;;  pop de\n;;  or d | and d | xor d\n;;\n;; At O1 Level, this happens only with 8 bit operations between h and a\n\nOLEVEL: 1\nOFLAG: 12\n\nREPLACE {{\n ld h, a\n pop af\n $1 h\n}}\n\nIF {{\n  ($1 IN (or, and, xor))\n}}\n\nWITH {{\n  pop de\n  $1 d\n}}\n" },
  { "012_o1_ld_hl_push_pop_de.opt",
    ";; Replaces sequence:\n;;  ld hl, XX\n;;  push hl\n;;  ld hl, YY\n;;  pop de\n;; with\n;;  ld de, XX\n;;  ld hl, YY\n\nOLEVEL: 1\nOFLAG: 13\n\nREPLACE {{\n  ld hl, $1\n  push hl\n  ld hl, $2\n  pop de\n}}\n\nIF {{\n}}\n\nWITH {{\n ld de, $1\n ld hl, $2\n}}\n\n" },
  { "013_o1_neg_neg.opt",
    ";; Replaces sequence:\n;;  neg\n;;  neg\n;; with\n;;  ; nop  ;; double neg can be removed\n\nOLEVEL: 1\nOFLAG: 13\n\nREPLACE {{\n  neg\n  neg\n}}\n\nWITH {{\n}}\n" },
  { "014_o1_or_sbc_a_a.opt",
    ";; Replaces sequence:\n;;  or|xor|and a\n;;  sbc a, a\n;; with\n;;  xor a\n\nOLEVEL: 1\nOFLAG: 14\n\nREPLACE {{\n  $1 a\n  sbc a, a\n}}\n\nIF {{\n  ($1 IN (or, and, xor))\n}}\n\nWITH {{\n  xor a\n}}\n\n" },
  { "015_o3_ld_r_n_not_required.opt",
    ";; Removes sequence\n;;  ld a, XXXX\n;; if a is not used later\n\nOLEVEL: 3\nOFLAG: 15\n\nREPLACE {{\n  ld a, $1\n}}\n\nIF {{\n   !IS_REQUIRED(a)\n}}\n\nWITH {{\n}}\n\n" },
  { "016_o1_xor_a_jp_z.opt",
    ";; Replaces sequence:\n;;  or|xor|and a\n;;  sbc a, a\n;; with\n;;  xor a\n\nOLEVEL: 1\nOFLAG: 17\n\nREPLACE {{\n  xor a\n  $1 z, $2\n}}\n\nIF {{\n  ($1 IN (jp, jr))\n}}\n\nWITH {{\n  $1 $2\n}}\n\n" },
  { "017_jp_cond_jp_labell.opt",
    ";; Replace sequence:\n;;  jp <condition>, __LABEL\n;;  jp OTHER\n;; __LABEL:\n;;\n;; With:\n;;  jp !<condition>, OTHER\n\nOLEVEL: 1\nOFLAG: 17\n\nREPLACE {{\n  $1 $2, $3\n  $4 $5\n$3:\n}}\n\n;; Defines $4 as the negated condition\nDEFINE {{\n  $6 = (($2 == nc) && c) || (($2 == c) && nc) || (($2 == nz) && z) || (($2 == z) && nz)\n}}\n\nIF {{\n  $6 && (LEN($5) == 1) && (($1 == jp) || ($1 == jr)) && (($4 == jp) || ($4 == jr))\n}}\n\nWITH {{\n $4 $6, $5\n$3:\n}}\n" },
  { "018_EQ16_by_sbchl.opt",
    ";; Tries to optimize a == b for U/Integers\n;; Replace sequence:\n;;  call __EQ16\n;;  or a | and a\n;;  jp nz, ...\n;; With:\n;;  or a\n;;  sbc hl, de\n;;  jp z, ...\n\nOLEVEL: 1\nOFLAG: 18\n\nREPLACE {{\n  call __EQ16\n  $1 a\n  jp $2, $3\n}}\n\n;; Defines $4 as the negated condition\nDEFINE {{\n  $4 = (($2 == nz) && z) || nz\n}}\n\nIF {{\n  ($1 == or) || ($1 == and)\n}}\n\nWITH {{\n  or a\n  sbc hl, de\n  jp $4, $3\n}}\n" },
  { "019_sub1_jpnc_ora_jpz.opt",
    ";; Tries to optimize a == b for U/Bytes\n;; Replace sequence:\n;;  sub 1\n;;  jp nc, __LABEL | jp c, __LABEL\n;; With:\n;;  or a\n;;  jp nz, __LABEL | jp z, __LABEL\n\nOLEVEL: 1\nOFLAG: 19\n\nREPLACE {{\n sub 1\n $1 $2, $3\n}}\n\nDEFINE {{\n  $4 = (($2 == nc) && nz) || z\n}}\n\nIF {{\n  (($1 == jp) || ($1 == jr)) && (($2 == nc) || ($2 == c))\n}}\n\nWITH {{\n or a\n $1 $4, $3\n}}\n" },
  { "020_o1_bool_norm_empty.opt",
    ";; Remove the boolean normalization if it's done after calling\n;; certain routines that return the bool result already normalized.\n\n;; The sequence\n;;   sub 1\n;;   sbc a, a\n;;   inc a\n;; can be removed\n\nOLEVEL: 1\nOFLAG: 20\n\nREPLACE {{\n  $1\n  sub 1\n  sbc a, a\n  inc a\n}}\n\nWITH {{\n  $1\n}}\n\nIF {{\n  $1 IN (\"xor a\", \"ld a, 0\",\n  \"call .core.__GEF\", \"call .core.__LEI16\", \"call .core.__LEI8\", \"call .core.__LTI8\",\n  \"call .core.__ANDF\", \"call .core.__EQF\", \"call .core.__GTF\", \"call .core.__LTI16\",\n  \"call .core.__LEF\", \"call .core.__LEI32\", \"call .core.__LTF\", \"call .core.__LTI32\",\n  \"call .core.__NEF\", \"call .core.__NOTF\", \"call .core.__ORF\", \"call .core.__XORF\",\n  \"call .core.__STREQ\", \"call .core.__STRNE\", \"call .core.__STRLT\", \"call .core.__STRLE\",\n  \"call .core.__STRGT\", \"call .core.__STRGE\")\n}}\n" },
  { "021_o1_bool_norm_neg.opt",
    ";; The sequence:\n;;   sbc a, a   ; A is either 0 or -1\n;;   sub 1\n;;   sbc a, a\n;;   inc a\n;; can be replaced by\n;;   neg        ; A is either 0 or 1\n\nOLEVEL: 1\nOFLAG: 21\n\nREPLACE {{\n  $1\n  sub 1\n  sbc a, a\n  inc a\n}}\n\nWITH {{\n  $1\n  neg\n}}\n\nIF {{\n    $1 IN (\"sbc a, a\", \"call .core.__NOT32\", \"call .core.__XOR8\", \"call .core.__XOR16\", \"call .core.__XOR32\")\n}}\n" },
  { "022_insr_a_or_a.opt",
    ";; Replace sequence:\n;; and X|or X|xor X|sub X|cp X|dec a|inc a\n;; or a\n;;\n;; With:\n;; and X|or X|xor X|sub X|cp X|dec a|inc a\n\nOLEVEL: 1\nOFLAG: 22\n\nREPLACE {{\n  $1 $2\n  $3 a\n}}\n\nIF {{\n  (($3 == or) || ($3 == and)) &&\n  (($1 == or) || ($1 == sub) || ($1 == and) || ($1 == xor) || ($1 == cp) ||\n  (($2 == a) && (($1 == dec) || ($1 == inc))))\n}}\n\nWITH {{\n  $1 $2\n}}\n" },
  { "023_ld_hl_bc_outl.opt",
    ";; Replace sequence:\n;;  ld hl, (NN) | ld hl, NN | pop hl\n;;  ld b, h\n;;  ld c, l\n;;  out (c), a | in a, (c)\n;; With:\n;;  ld bc, (NN) | ld bc, NN | pop bc\n;;  out (c), a | in a, (c)\n\nOLEVEL: 1\nOFLAG: 23\n\nREPLACE {{\n  $1 hl$2\n  ld b, h\n  ld c, l\n  $3\n}}\n\nIF {{\n  (($1 == ld) || ($1 == pop)) && (($3 == \"out (c), a\") || ($3 == \"in a, (c)\"))\n}}\n\nWITH {{\n  $1 bc$2\n  $3\n}}\n" },
  { "024_o1_bool_norm_duble_neg.opt",
    ";; The sequence:\n;;   sbc a, a   ; A is either 0 or -1\n;;   sub 1\n;;   sbc a, a\n;;   neg\n;; can be replaced by\n;;   sbc a, a   ; A is either 0 or -1\n;;   inc a\n\nOLEVEL: 1\nOFLAG: 24\n\nREPLACE {{\n  sbc a, a\n  sub 1\n  sbc a, a\n  neg\n}}\n\nWITH {{\n  sbc a, a\n  inc a\n}}\n" },
  { "025_ld_h_a_oper_A.opt",
    ";; Replace sequence:\n;; ld h, r  (r != a)\n;; ld a, X\n;; or/and/cp/add a,/sbc a,/sub h\n;;\n;; With:\n;; ld a, X\n;; or|xor|and|cp|add|sub r\n\n\nOLEVEL: 1\nOFLAG: 25\n\nREPLACE {{\n  ld h, $1\n  ld a, $2\n  $3 h\n}}\n\nIF {{\n  ($1 <> a) && (($3 == or) || ($3 == xor) || ($3 == and) || ($3 == cp) || ($3 == sub) || ($3 == \"add a,\") || ($3 == \"sbc a,\"))\n}}\n\nWITH {{\n  ld a, $2\n  $3 $1\n}}\n" },
  { "027_ld_h_a_oper_A.opt",
    ";; Replace sequence:\n;; ld h, X\n;; or h | and h\n;;\n;; With:\n;; or X | and X\n\nOLEVEL: 1\nOFLAG: 27\n\nREPLACE {{\n  ld h, $1\n  $2 h\n}}\n\nIF {{\n  ($2 IN (or, xor, and, cp, sub, \"add a,\", \"sbc a,\"))\n}}\n\nWITH {{\n  $2 $1\n}}\n" },
  { "028_o2_pop_up.opt",
    ";; Replace sequence:\n;; <instruction>\n;; pop rr\n;;\n;; With:\n;; pop rr\n;; <instruction>\n;;\n;; This frees the stack ASAP and hopefully clash against a PUSH\n\n\nOLEVEL: 2\nOFLAG: 28\n\nREPLACE {{\n  $2\n  pop $1\n}}\n\nIF {{\n  !(INSTR($2) IN (jp, jr, ret, call, djnz, rst)) && !NEEDS($2, (sp, $1)) && !IS_LABEL($2) &&\n  OP1($2) <> \"sp\" && OP2($2) <> \"sp\"\n}}\n\nWITH {{\n  pop $1\n  $2\n}}\n" },
  { "028_o3_pop_up.opt",
    ";; Replace sequence:\n;; <instruction>\n;; pop rr\n;;\n;; With:\n;; pop rr\n;; <instruction>\n;;\n;; This frees the stack ASAP and hopefully clash against a PUSH\n\nOLEVEL: 3\nOFLAG: 28\n\nREPLACE {{\n  $2\n  pop $1\n}}\n\nIF {{\n  !(INSTR($2) IN (jp, jr, ret, call, djnz, rst)) && !NEEDS($2, (sp, $1)) && !IS_LABEL($2)\n  && OP1($2) <> \"sp\"\n}}\n\nWITH {{\n  pop $1\n  $2\n}}\n" },
  { "029_cp_0_or_a.opt",
    ";; Replace sequence:\n;; sub 0|cp 0\n;;\n;; With:\n;; or a\n\nOLEVEL: 1\nOFLAG: 29\n\nREPLACE {{\n  $1 0\n}}\n\nIF {{\n  ($1 == cp) || ($1 == sub)\n}}\n\nWITH {{\n  or a\n}}\n" },
  { "030_ora_jp_nc_jp.opt",
    ";; Replace sequence:\n;; or a | and a\n;; jp nc, X | jr nc, X\n;;\n;; With:\n;; jp X | jr X\n\nOLEVEL: 1\nOFLAG: 30\n\nREPLACE {{\n  $1 a\n  $2 nc, $3\n}}\n\nIF {{\n  ($1 IN (or, xor, and, cp, sub)) && (($2 == jp) || ($2 == jr))\n}}\n\nWITH {{\n  $2 $3\n}}\n" },
  { "031_jpX_Y_jpX.opt",
    ";; Removes useless (jumped over) instructions\n;; Replace sequence:\n;; jp X | jr X\n;; YYYY\n;;\n;; With:\n;; jp X | jr X\n;;\n;; YYYY must not be a label\n\nOLEVEL: 1\nOFLAG: 31\n\nREPLACE {{\n  $1 $2\n  $3\n}}\n\nIF {{\n  (($1 == jp) || ($1 == jr)) && (!IS_LABEL($3)) && (LEN($2) == 1) && (!IS_ASM($3))\n}}\n\nWITH {{\n  $1 $2\n}}\n" },
  { "032_call_LOADSTR_ld_a1.opt",
    ";; Replace sequence:\n;; call __LOADSTR\n;; ld a, 1\n;; call __PRINTSTR\n;;\n;; With:\n;; xor a\n;; call __PRINTSTR\n\nOLEVEL: 1\nOFLAG: 32\n\nREPLACE {{\n  call __LOADSTR\n  ld a, 1\n  call __PRINTSTR\n}}\n\nWITH {{\n  xor a\n  call __PRINTSTR\n}}\n" },
  { "050_o1_ld_a_ld_h_pop.opt",
    ";; Replace sequence:\n;; ld a, X\n;; ld h, a\n;; ld a, Y\n;;\n;; With:\n;; ld h, X\n;; ld a, Y\n;;\n;; Whenever X is (hl), (ix + n) or a register\n\n\nOLEVEL: 1\nOFLAG: 50\n\nREPLACE {{\n  ld a, $4\n  ld h, a\n  ld a, $3\n}}\n\nIF {{\n  (($4 == \"(hl)\") || (IS_INDIR($4)) || (IS_REG8($4)))\n}}\n\nWITH {{\n  ld h, $4\n  ld a, $3\n}}\n" },
  { "051_o1_ld_a_ld_h_a_pop.opt",
    ";; Replace sequence:\n;; ld a, X\n;; ld h, a\n;; pop af\n;;\n;; With:\n;; ld h, X\n;; pop af\n;;\n;; Whenever X is (hl), (ix + n) a number or a register\n\n\nOLEVEL: 1\nOFLAG: 50\n\nREPLACE {{\n  ld a, $1\n  ld h, a\n  pop af\n}}\n\nIF {{\n  (($1 == \"(hl)\") || (IS_INDIR($1)) || (IS_REG8($1)))\n}}\n\nWITH {{\n  pop af\n  ld h, $1\n}}\n" },
  { "052_o3_ldhl_ld_a_l.opt",
    ";; Replaces sequence:\n;; ld hl, (_XXXX)\n;; ld a, l\n;;\n;; With:\n;; ld a, (_XXXX)\n\nOLEVEL: 3\nOFLAG: 52\n\nREPLACE {{\n ld hl, ($1)\n ld a, l\n}}\n\nIF {{\n  !IS_REQUIRED(hl)\n}}\n\nWITH {{\n ld a, ($1)\n}}\n" },
  { "053_o1_ldh_nnn.opt",
    ";; Replaces sequence:\n;; ld a, (_XXXX)\n;; ld h, a\n;;\n;; With:\n;; ld hl, (_XXXX - 1)\n\nOLEVEL: 1\nOFLAG: 53\n\nREPLACE {{\n ld a, ($1)\n ld h, a\n pop af\n}}\n\n\nWITH {{\n pop af\n ld hl, ($1 - 1)\n}}\n" },
  { "054_o3_ld_a_N_ld_hl_a.opt",
    ";; Replaces sequence:\n;; ld hl, (_XXXX)\n;; ld a, l\n;;\n;; With:\n;; ld a, (_XXXX)\n\nOLEVEL: 3\nOFLAG: 54\n\nREPLACE {{\n ld a, $1\n ld hl, ($2)\n ld (hl), a\n}}\n\nIF {{\n  !IS_REQUIRED(a) && IS_IMMED($1)\n}}\n\nWITH {{\n ld hl, ($2)\n ld (hl), $1\n}}\n" },
  { "100_o3_ld_rr_N_ld_ss_N.opt",
    ";; Removes useless LD's\n;; Tries to guess the value of the 1st and 2nd operands.\n;; If they're the same, this LD is useless\n\nOLEVEL: 3\nOFLAG: 100\n\nREPLACE {{\n  ld $1, $2\n}}\n\nIF {{\n  (GVAL($1) == GVAL($2)) ||\n  ((IS_REG8($1) || IS_REG8($2)) &&\n   (LOVAL(GVAL($1)) == LOVAL(GVAL($2)))\n   )\n}}\n\nWITH {{\n}}\n" },
  { "101_o3_ld_rr_N_ld_h_r_ld_l_r.opt",
    ";; Replace sequence:\n;; ld hl, N\n;; ld b, h\n;; ld c, l\n;;\n;; With:\n;; ld bc, N\n;;\n;; If hl is not required later\n;; also works with any other 16bit register\n\nOLEVEL: 3\nOFLAG: 101\n\nREPLACE {{\n  ld $1, $2\n  ld $3, $4\n  ld $5, $6\n}}\n\nIF {{\n  (\n  IS_REG16($1) && IS_REG16($7) && !IS_REQUIRED($1)\n   && IS_REG8($5) && IS_REG8($3) && IS_REG8($4) && IS_REG8($6)\n   && ((HIREG($1) == $4 && HIREG($7) == $3 && LOREG($1) == $6 && LOREG($7) == $5) ||\n      (HIREG($1) == $6 && HIREG($7) == $5 && LOREG($1) == $4 && LOREG($7) == $3))\n  )\n}}\n\nDEFINE {{\n  $7 = IS_REG16($3 + $5) && ($3 + $5) || ($5 + $3)\n}}\n\nWITH {{\n  ld $7, $2\n}}\n" },
  { "102_o3_ld_r_n_ld_r_n2.opt",
    ";; Removes useless LD's\n;; Replaces;\n;; LD r, XXX\n;; LD r, YYY\n;; With:\n;; LD r, YYY\n\nOLEVEL: 3\nOFLAG: 102\n\nREPLACE {{\n  ld $1, $2\n  ld $1, $3\n}}\n\nWITH {{\n  ld $1, $3\n}}\n" },
  { "103_o3_or_and_a.opt",
    ";; Removes useless AND, OR a\n\nOLEVEL: 3\nOFLAG: 103\n\nREPLACE {{\n  $1 $2\n}}\n\nIF {{\n  ($1 IN (and, or)) &&\n  (($2 == a) || (!IS_REQUIRED(a))) &&\n  !IS_REQUIRED(f)\n}}\n\nWITH {{\n}}\n" },
  { "103_o3_xor_a.opt",
    ";; Removes useless XOR a\n\nOLEVEL: 3\nOFLAG: 103\n\nREPLACE {{\n  xor a\n}}\n\nIF {{\n  (GVAL(a) == 0) && ((FLAGVAL(c) == 0 && FLAGVAL(z) == 1) || !IS_REQUIRED(f))\n}}\n\nWITH {{\n}}\n" },
  { "104_o3_opt27.opt",
    ";; Replaces\n;;\n;; ld r, XX\n;; cp r | sub r | and r | or r | xor r\n;;\n;; With\n;; cp XX | sub XX | and XX | or XX | xor XX\n;;\n;; IF r != a, and r is not required later\n;;\n;; Formerly OPT27\n\nOLEVEL: 3\nOFLAG: 104\n\nREPLACE {{\n  ld $1, $2\n  $3 $1\n}}\n\nIF {{\n    ($1 <> a) &&\n    !IS_REQUIRED($1) && !IS_REQUIRED(f) &&\n    ($3 IN (cp, or, and, xor, sub))\n}}\n\nWITH {{\n  $3 $2\n}}\n" },
  { "105_o3_opt27.opt",
    ";; Replaces\n;;\n;; ld r, XX\n;; add a, r | adc a, r | sbc a, r\n;;\n;; With\n;; add a, XX | adc a, XX | sbc a, XX\n;;\n;; IF r != a, and r is not required later\n;;\n;; Formerly OPT27\n\nOLEVEL: 3\nOFLAG: 105\n\nREPLACE {{\n  ld $1, $2\n  $3 a, $1\n}}\n\nIF {{\n    ($1 <> a) &&\n    !IS_REQUIRED($1) && !IS_REQUIRED(f) &&\n    ($3 IN (add, adc, sbc))\n}}\n\nWITH {{\n  $3 a, $2\n}}\n" },
  { "106_o3_exdehl.opt",
    ";; Replaces\n;;\n;; ld de, nn\n;;\n;; With\n;; ex de, hl\n;;\n;; if hl is no longer required, and guessed val of hl is nn\n\nOLEVEL: 3\nOFLAG: 106\n\nREPLACE {{\n  ld de, $1\n}}\n\nIF {{\n    GVAL(hl) == GVAL($1) && !IS_REQUIRED(hl)\n}}\n\nWITH {{\n  ex de, hl\n}}\n" },
  { "107_o3_exdehl_ldde.opt",
    ";; Replaces\n;;\n;; ld hl, nn\n;; ex de, hl\n;;\n;; With\n;; ld de, nn\n;;\n;; if hl is no longer required\n\nOLEVEL: 3\nOFLAG: 107\n\nREPLACE {{\n  ld hl, $1\n  ex de, hl\n}}\n\nIF {{\n    !IS_REQUIRED(hl)\n}}\n\nWITH {{\n  ld de, $1\n}}\n" },
  { "108_o3_inc_dec.opt",
    ";; Replaces\n;;\n;; ld rr, nn\n;;\n;; With\n;; inc / dec rr\n;;\n;; If the previous known value of rr is nn - / + 1\n\n\nOLEVEL: 3\nOFLAG: 108\n\nREPLACE {{\n   ld $1, $2\n}}\n\nDEFINE {{\n   $3 = ($2 == GVAL($1) .+ 1) && \"inc\" || ($2 == GVAL($1) .- 1) && \"dec\"\n}}\n\nIF {{\n    IS_REG16($1) && $3 <> \"\"\n}}\n\nWITH {{\n  $3 $1\n}}\n" },
  { "109_o4_ld_mem_op_ld_mem.opt",
    ";; Removes useless operation\n;; Tries to guess if the result of the operation LD, OR, AND, XOR, ADC, ADD, SBC is later used\n\nOLEVEL: 4\nOFLAG: 109\n\nREPLACE {{\n  $1 $2, $3\n}}\n\nIF {{\n($2 <> sp) && ($2 <> ix) && !IS_REQUIRED($2) &&\n ($1 == ld || (!IS_REQUIRED(f) && ($1 == add || $1 == adc || $1 == sbc)))\n}}\n\nWITH {{\n}}\n" },
  { "110_o4_ld_mem_op_ld_mem.opt",
    ";; Removes useless LD's\n;; Tries to guess the value of the 1st and 2nd operands.\n;; If they're the same, this LD is useless\n\nOLEVEL: 4\nOFLAG: 110\n\nREPLACE {{\n  $1 $2\n}}\n\nIF {{\n ((($1 == inc || $1 == dec) && !IS_REQUIRED($2))\n || ($1 == sub && !IS_REQUIRED(a))\n ) && ($2 <> sp) && !IS_REQUIRED(f)\n}}\n\nWITH {{\n}}\n" },
};
const int PEEP_EMBEDDED_OPTS_COUNT =
    (int)(sizeof(PEEP_EMBEDDED_OPTS) / sizeof(PEEP_EMBEDDED_OPTS[0]));
